<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="project_perry" params="parent prefix *origin">

        <joint name="base_joint" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="base_link"/>
        </joint>

        <!-- Constants for robot dimensions -->
        <xacro:property name="mass" value="1"/> <!-- arbitrary value for mass -->
        <xacro:property name="base_width" value="1"/>
        <xacro:property name="base_height" value="0.6"/>
        <xacro:property name="platter_radius" value="0.75"/>
        <xacro:property name="platter_height" value="0.1"/>
        <xacro:property name="width" value="0.1"/> <!-- Square dimensions (widthxwidth) of beams -->
        <xacro:property name="height1" value="2"/> <!-- Link 1 -->
        <xacro:property name="height2" value="1"/> <!-- Link 2 -->
        <xacro:property name="height3" value="1"/> <!-- Link 3 -->
        <xacro:property name="gripper_width" value="0.4"/>
        <xacro:property name="gripper_breadth" value="0.1"/>
        <xacro:property name="gripper_thickness" value="0.05"/>
        <xacro:property name="finger_length" value="0.2"/>
        <xacro:property name="finger_thickness" value="0.05"/>
        <xacro:property name="axel_offset" value="0.05"/> <!-- Space btw top of beam and the each joint -->


        <!-- Generated using onshape-to-robot -->
        <!-- Base Link -->
        <link name="base_link">
            <collision>
                <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width} ${base_width} ${base_height}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width} ${base_width} ${base_height}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
                        izz="${mass / 12.0 * (base_width*base_width + base_width*base_width)}"/>
            </inertial>
        </link>

        <joint name="base_yaw_joint" type="continuous">
            <parent link="base_link"/>
            <child link="shoulder_link"/>
            <origin xyz="0 0 ${base_height - axel_offset}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="0.7"/>
            <limit effort="100" velocity="1.0"/>
        </joint>

        <!-- Middle Link -->
        <link name="shoulder_link">
            <collision>
                <origin xyz="0 0 ${platter_height/2 + axel_offset}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${platter_radius}" length="${platter_height}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${platter_height/2 + axel_offset}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${platter_radius}" length="${platter_height}"/>
                </geometry>
                <material name="yellow"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${platter_height/2 - axel_offset}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (3*platter_radius*platter_radius + platter_height*platter_height)}"
                        ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (3*platter_radius*platter_radius + platter_height*platter_height)}"
                        iyz="0.0"
                        izz="${mass / 2.0 * platter_radius*platter_radius}"/>
            </inertial>
        </link>

        <joint name="base_pitch_joint" type="revolute">
            <parent link="shoulder_link"/>
            <child link="humerus_link"/>
            <origin xyz="0 0 ${platter_height + axel_offset*2}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.7"/>
            <limit lower="${-pi/2.0}" upper="${pi/2.0}" effort="100" velocity="1.0"/>
        </joint>

        <!-- Top Link -->
        <link name="humerus_link">
            <collision>
                <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height3}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height3}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
                        izz="${mass / 12.0 * (width*width + width*width)}"/>
            </inertial>
        </link>

        <joint name="elbow_0_joint" type="revolute">
            <parent link="humerus_link"/>
            <child link="wrist_link"/>
            <origin xyz="0 0 ${height3}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.7"/>
            <limit lower="${-3*pi/4.0}" upper="${3*pi/4.0}" effort="100" velocity="1.0"/>
        </joint>

        <!-- Wrist Link -->
        <link name="wrist_link">
            <collision>
                <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height3}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height3}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
                        izz="${mass / 12.0 * (width*width + width*width)}"/>
            </inertial>
        </link>

        <joint name="gripper_wrist_fixture" type="fixed">
            <parent link="wrist_link"/>
            <child link="gripper_link"/>
            <origin xyz="0 0 ${height3 - width}" rpy="0 0 0"/>
        </joint>

        <!-- Gripper Link -->
        <link name="gripper_link">
            <collision>
                <origin xyz="0 0 ${gripper_thickness/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${gripper_width} ${gripper_breadth} ${gripper_thickness}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 ${gripper_thickness/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${gripper_width} ${gripper_breadth} ${gripper_thickness}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <inertial>
                <origin xyz="0 0 ${gripper_thickness/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (gripper_width*gripper_breadth + gripper_thickness*gripper_thickness)}" ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (gripper_thickness*gripper_thickness + gripper_width*gripper_breadth)}" iyz="0.0"
                        izz="${mass / 12.0 * (gripper_width*gripper_breadth + gripper_width*gripper_breadth)}"/>
            </inertial>
        </link>

        <joint name="gripper" type="prismatic">
            <origin xyz="${-gripper_width/2 - width/2} 0 ${gripper_thickness}" rpy="0 0 0"/>
            <parent link="gripper_link"/>
            <child link="finger_left_link"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="0.7"/>
            <limit lower="0" upper="${gripper_width/2 - finger_thickness}" effort="100" velocity="1.0"/>
        </joint>

        <joint name="gripper_mimic" type="prismatic">
            <origin xyz="${-gripper_width/2 - width/2} 0 ${gripper_thickness}" rpy="0 0 0"/>
            <parent link="gripper_link"/>
            <child link="finger_right_link"/>
            <mimic joint="gripper" multiplier="-1" offset="0.5"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="0.7"/>
            <limit lower="${-gripper_width/2 + finger_thickness}" upper="0" effort="100" velocity="1.0"/>
        </joint>

        <!-- Finger Links -->
        <link name="finger_left_link">
            <collision>
                <origin xyz="${finger_thickness*1.5} 0 ${finger_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${finger_thickness} ${gripper_breadth} ${finger_length}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="${finger_thickness*1.5} 0 ${finger_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${finger_thickness} ${gripper_breadth} ${finger_length}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <inertial>
                <origin xyz="${finger_thickness*1.5} 0 ${finger_length/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (finger_thickness*gripper_breadth + finger_length*finger_length)}" ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (finger_length*finger_length + finger_thickness*gripper_breadth)}" iyz="0.0"
                        izz="${mass / 12.0 * (finger_thickness*gripper_breadth + finger_thickness*gripper_breadth)}"/>
            </inertial>
        </link>
        <link name="finger_right_link">
            <collision>
                <origin xyz="${-finger_thickness*1.5} 0 ${finger_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${finger_thickness} ${width} ${finger_length}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="${-finger_thickness*1.5} 0 ${finger_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${finger_thickness} ${width} ${finger_length}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <inertial>
                <origin xyz="${-finger_thickness*1.5} 0 ${finger_length/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                        ixx="${mass / 12.0 * (finger_thickness*width + finger_length*finger_length)}" ixy="0.0" ixz="0.0"
                        iyy="${mass / 12.0 * (finger_length*finger_length + finger_thickness*width)}" iyz="0.0"
                        izz="${mass / 12.0 * (finger_thickness*width + finger_thickness*width)}"/>
            </inertial>
        </link>

    </xacro:macro>

</robot>
