# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - project_perry_controller
    - gripper_controller

  project_perry_controller:
    type: FollowJointTrajectory
    joints:
      - base_yaw
      - base_pitch
      - elbow_pitch
      - wrist_pitch
    action_ns: follow_joint_trajectory
    default: true

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - wrist_roll
    action_ns: follow_joint_trajectory
    default: true