# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_base_controller
    - gripper_controller

  arm_base_controller:
    type: FollowJointTrajectory
    joints:
      - base_yaw_joint
      - base_pitch_joint
      - elbow_0_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: GripperCommand
    joints:
      - gripper
    action_ns: gripper_cmd
    default: true