# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    project_perry_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

project_perry_controller:
  ros__parameters:
    joints:
      - base_yaw
      - base_pitch
      - elbow_pitch
      - wrist_pitch
    command_interfaces:
      []
    state_interfaces:
      []
gripper_controller:
  ros__parameters:
    joints:
      - wrist_roll
    command_interfaces:
      []
    state_interfaces:
      []