controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    project_perry_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

project_perry_controller:
  ros__parameters:
    joints:
      - base_yaw
      - base_pitch
      - elbow_pitch
      - wrist_pitch

    command_interfaces:
      - velocity
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    set_last_command_interface_value_as_state_on_activation: true

    constraints:
      base_yaw:
        goal: 1.0
        trajectory: 1.0
      base_pitch:
        goal: 1.0
        trajectory: 1.0
      elbow_pitch:
        goal: 1.0
        trajectory: 1.0
      wrist_pitch:
        goal: 1.0
        trajectory: 1.0
      goal_time: 20.0
      stopped_velocity_tolerance: 0.01

gripper_controller:
  ros__parameters:
    joints:
      - wrist_roll

    command_interfaces:
      - velocity
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    set_last_command_interface_value_as_state_on_activation: true

    constraints:
      wrist_roll:
        goal: 1.0
        trajectory: 1.0
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01