# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_base_controller:
  ros__parameters:
    joints:
      - base_yaw_joint
      - base_pitch_joint
      - elbow_0_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: gripper