name: Build packages

on:
  push:
    branches:
      #- main TODO: Switch back
      - initial_configs

jobs:
  build-description:
    permissions:
      contents: write
      packages: read

    defaults:
      run:
        working-directory: ./umrt-project-perry-description

    uses: UMRoboticsTeam/umrt-ci-cd/.github/workflows/ros-build.yaml@main
    with:
      build_image: ghcr.io/umroboticsteam/umrt-build:v0.0.16
      publish_image: ghcr.io/umroboticsteam/umrt-apt-image:latest
      publish_repo: UMRoboticsTeam/umrt-apt-repo
    secrets:
      APT_SIGNING_PUBKEY: ${{ secrets.APT_SIGNING_PUBKEY }}
      APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}
      APT_DEPLOY_KEY: ${{ secrets.APT_DEPLOY_KEY }}
